- name: Install package on Debian-based systems
  ansible.builtin.apt:
    name: "{{ package_name }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install package on RedHat-based systems
  ansible.builtin.yum:
    name: "{{ package_name }}"
    state: present
  when: ansible_os_family == "RedHat"